"""empty message

Revision ID: 19932ffaaa12
Revises: d57ae6fbbdae
Create Date: 2019-03-18 23:12:34.777444

"""

# revision identifiers, used by Alembic.
revision = '19932ffaaa12'
down_revision = 'd57ae6fbbdae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('tin_number', sa.String(), nullable=True))
    op.drop_column('service_provider', 'ura_tin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('ura_tin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('service_provider', 'tin_number')
    # ### end Alembic commands ###
