"""empty message

Revision ID: 337342b63627
Revises: 5e602d2c6886
Create Date: 2019-04-08 20:40:48.011127

"""

# revision identifiers, used by Alembic.
revision = '337342b63627'
down_revision = '5e602d2c6886'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('vechile_registration_number', sa.String(), nullable=True))
    op.drop_column('incident', 'registration_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('registration_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('incident', 'vechile_registration_number')
    # ### end Alembic commands ###
