"""empty message

Revision ID: 34108c69d668
Revises: d9727628f262
Create Date: 2019-03-19 11:45:20.540575

"""

# revision identifiers, used by Alembic.
revision = '34108c69d668'
down_revision = 'd9727628f262'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'location')
    # ### end Alembic commands ###
