"""empty message

Revision ID: 40600e641cea
Revises: 7c4d97c04ef6
Create Date: 2019-03-18 21:49:00.233004

"""

# revision identifiers, used by Alembic.
revision = '40600e641cea'
down_revision = '7c4d97c04ef6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('membership_number', sa.String(), nullable=True))
    op.drop_column('incident', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('incident', 'membership_number')
    # ### end Alembic commands ###
