"""empty message

Revision ID: 48056480b3c0
Revises: 34108c69d668
Create Date: 2019-03-19 13:39:28.376662

"""

# revision identifiers, used by Alembic.
revision = '48056480b3c0'
down_revision = '34108c69d668'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('issue', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'issue')
    # ### end Alembic commands ###
