"""empty message

Revision ID: 4e42e3edadf3
Revises: a3c26aac1830
Create Date: 2019-03-20 07:22:04.090775

"""

# revision identifiers, used by Alembic.
revision = '4e42e3edadf3'
down_revision = 'a3c26aac1830'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('service', sa.Column('operating_time', sa.String(), nullable=True))
    op.add_column('service', sa.Column('service_photo', sa.String(), nullable=True))
    op.add_column('service', sa.Column('service_structure', sa.String(), nullable=True))
    op.drop_column('service', 'operation_type')
    op.drop_column('service', 'operating_type')
    op.drop_column('service', 'service_organisation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('service_organisation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('service', sa.Column('operating_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('service', sa.Column('operation_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('service', 'service_structure')
    op.drop_column('service', 'service_photo')
    op.drop_column('service', 'operating_time')
    op.drop_column('service', 'contact')
    # ### end Alembic commands ###
