"""empty message

Revision ID: 7c8a8dcb1cfa
Revises: 48056480b3c0
Create Date: 2019-03-19 21:31:56.306805

"""

# revision identifiers, used by Alembic.
revision = '7c8a8dcb1cfa'
down_revision = '48056480b3c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('dob', sa.String(), nullable=True))
    op.add_column('client', sa.Column('locaton', sa.String(), nullable=True))
    op.add_column('client', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('client', sa.Column('place_of_work', sa.String(), nullable=True))
    op.add_column('client', sa.Column('telephone_alternative', sa.String(), nullable=True))
    op.drop_column('client', 'membership')
    op.drop_column('client', 'service_duration')
    op.add_column('service', sa.Column('account_manager', sa.String(), nullable=True))
    op.add_column('service', sa.Column('operating_type', sa.String(), nullable=True))
    op.add_column('service', sa.Column('operation_type', sa.String(), nullable=True))
    op.add_column('service', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_service_timestamp'), 'service', ['timestamp'], unique=False)
    op.add_column('vehicle', sa.Column('body_type', sa.String(), nullable=True))
    op.add_column('vehicle', sa.Column('car_make', sa.String(), nullable=True))
    op.add_column('vehicle', sa.Column('chassis_number', sa.String(), nullable=True))
    op.add_column('vehicle', sa.Column('fuel_type', sa.String(), nullable=True))
    op.add_column('vehicle', sa.Column('registration_number', sa.String(), nullable=True))
    op.add_column('vehicle', sa.Column('year_of_make', sa.String(), nullable=True))
    op.drop_constraint(u'vehicle_client_id_fkey', 'vehicle', type_='foreignkey')
    op.drop_column('vehicle', 'engine_size')
    op.drop_column('vehicle', 'mileage')
    op.drop_column('vehicle', 'social_number_plate')
    op.drop_column('vehicle', 'transmission')
    op.drop_column('vehicle', 'manufacture_year')
    op.drop_column('vehicle', 'client_id')
    op.drop_column('vehicle', 'fuel')
    op.drop_column('vehicle', 'model')
    op.drop_column('vehicle', 'registration_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('registration_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('fuel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('manufacture_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('transmission', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('social_number_plate', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('mileage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vehicle', sa.Column('engine_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'vehicle_client_id_fkey', 'vehicle', 'client', ['client_id'], ['id'])
    op.drop_column('vehicle', 'year_of_make')
    op.drop_column('vehicle', 'registration_number')
    op.drop_column('vehicle', 'fuel_type')
    op.drop_column('vehicle', 'chassis_number')
    op.drop_column('vehicle', 'car_make')
    op.drop_column('vehicle', 'body_type')
    op.drop_index(op.f('ix_service_timestamp'), table_name='service')
    op.drop_column('service', 'timestamp')
    op.drop_column('service', 'operation_type')
    op.drop_column('service', 'operating_type')
    op.drop_column('service', 'account_manager')
    op.add_column('client', sa.Column('service_duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('membership', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client', 'telephone_alternative')
    op.drop_column('client', 'place_of_work')
    op.drop_column('client', 'occupation')
    op.drop_column('client', 'locaton')
    op.drop_column('client', 'dob')
    # ### end Alembic commands ###
