"""empty message

Revision ID: 8955a292b8fc
Revises: 4e42e3edadf3
Create Date: 2019-03-20 09:32:29.602227

"""

# revision identifiers, used by Alembic.
revision = '8955a292b8fc'
down_revision = '4e42e3edadf3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('car_make', sa.String(), nullable=True))
    op.add_column('incident', sa.Column('contact_number', sa.String(), nullable=True))
    op.add_column('incident', sa.Column('photo_one', sa.String(), nullable=True))
    op.add_column('incident', sa.Column('photo_three', sa.String(), nullable=True))
    op.add_column('incident', sa.Column('photo_two', sa.String(), nullable=True))
    op.add_column('incident', sa.Column('registration_number', sa.String(), nullable=True))
    op.drop_column('incident', 'defect')
    op.drop_column('incident', 'membership_number')
    op.drop_column('incident', 'photo_name')
    op.drop_column('incident', 'location')
    op.drop_column('incident', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incident', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incident', sa.Column('photo_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incident', sa.Column('membership_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incident', sa.Column('defect', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('incident', 'registration_number')
    op.drop_column('incident', 'photo_two')
    op.drop_column('incident', 'photo_three')
    op.drop_column('incident', 'photo_one')
    op.drop_column('incident', 'contact_number')
    op.drop_column('incident', 'car_make')
    # ### end Alembic commands ###
