"""empty message

Revision ID: 9cf171d2a7a9
Revises: 99015e852752
Create Date: 2019-03-19 08:30:49.458231

"""

# revision identifiers, used by Alembic.
revision = '9cf171d2a7a9'
down_revision = '99015e852752'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('service_organisation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service_organisation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'services_pkey')
    )
    op.drop_table('service')
    # ### end Alembic commands ###
