"""empty message

Revision ID: a3c26aac1830
Revises: 7c8a8dcb1cfa
Create Date: 2019-03-20 06:44:18.999161

"""

# revision identifiers, used by Alembic.
revision = 'a3c26aac1830'
down_revision = '7c8a8dcb1cfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('client', 'locaton')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('locaton', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client', 'location')
    # ### end Alembic commands ###
