"""empty message

Revision ID: ce3247e8a3ae
Revises: 5169d29e9b70
Create Date: 2019-03-18 23:06:25.617210

"""

# revision identifiers, used by Alembic.
revision = 'ce3247e8a3ae'
down_revision = '5169d29e9b70'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('photo_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_provider_timestamp'), 'service_provider', ['timestamp'], unique=False)
    op.drop_index('ix_server_provider_timestamp', table_name='server_provider')
    op.drop_table('server_provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_provider',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'server_provider_pkey')
    )
    op.create_index('ix_server_provider_timestamp', 'server_provider', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_service_provider_timestamp'), table_name='service_provider')
    op.drop_table('service_provider')
    # ### end Alembic commands ###
