"""empty message

Revision ID: d57ae6fbbdae
Revises: ce3247e8a3ae
Create Date: 2019-03-18 23:11:37.425569

"""

# revision identifiers, used by Alembic.
revision = 'd57ae6fbbdae'
down_revision = 'ce3247e8a3ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('ura_tin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_provider', 'ura_tin')
    # ### end Alembic commands ###
